//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace jb_test.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class iepb00h
    {
        public int Id { get; set; }
        public string od_id { get; set; }
        public string od_name { get; set; }
        public string od_name1 { get; set; }
        public decimal od_rate { get; set; }
        public decimal od_rate1 { get; set; }
        public decimal od_rate2 { get; set; }
        public decimal od_rate3 { get; set; }
        public string od_ymd { get; set; }
        public string ie_def { get; set; }
        public string ie_ymd { get; set; }
        public string ie_time { get; set; }
        public string ie_user { get; set; }
        public string ie_lymd { get; set; }
        public string ie_ltime { get; set; }
        public string ie_luser { get; set; }
        public string ie_cymd { get; set; }
        public string ie_ctime { get; set; }
        public string ie_cuser { get; set; }
        public string ie_cancel { get; set; }
        public string od_cu { get; set; }
        public string od_id1 { get; set; }
    }
}
